---

arch:
  - amd64
  - arm64

language: python
services: docker

install:
  - pip install -r requirements.txt

before_script:
  # Rename current directory to allow forked tests to work.
  - mv ../$(basename $PWD) ../borgbackup 2>/dev/null || true

env:
  - SCENARIO: default
  - SCENARIO: centos
  - SCENARIO: ubuntu
  - SCENARIO: lamp
  - SCENARIO: multiple
  - SCENARIO: clients_arm
  # - SCENARIO: clients
  # - SCENARIO: lamp
  # - SCENARIO: extra_opts
  # - SCENARIO: multiple

jobs:
  include:
    - os: linux
      arch: arm64
      env: SCENARIO=clients_arm
  exclude:
    - os: linux
      arch: amd64
      env: SCENARIO=clients_arm

script:
  - molecule test --scenario-name $SCENARIO

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
