---
language: python
services: docker

env:
  - SCENARIO: default
  - SCENARIO: centos
  - SCENARIO: ubuntu
  - SCENARIO: clients
  - SCENARIO: lamp
  - SCENARIO: multiple

#  - SCENARIO: lamp
#  - SCENARIO: extra_opts
#  - SCENARIO: multiple

install:
  - pip install -r requirements.txt

before_script:
  # Rename current directory to allow forked tests to work.
  - mv ../$(basename $PWD) ../borgbackup

script:
  - molecule test --scenario-name $SCENARIO

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
