---

arch:
  - amd64
  - arm64

language: python
services: docker

cache:
  pip: true
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install -r requirements.txt

before_script:
  # Rename current directory to allow forked tests to work.
  - mv ../$(basename $PWD) ../borgbackup 2>/dev/null || true

env:
  - SCENARIO: default
  - SCENARIO: centos
  - SCENARIO: ubuntu
  - SCENARIO: lamp
  - SCENARIO: multiple
  - SCENARIO: clients_arm
  # - SCENARIO: clients
  # - SCENARIO: lamp
  # - SCENARIO: extra_opts
  # - SCENARIO: multiple

jobs:
  exclude:
    # exclude jobs that should not be run on ARM
    - arch: arm64
      env: SCENARIO=default
    - arch: arm64
      env: SCENARIO=centos
    - arch: arm64
      env: SCENARIO=ubuntu
    - arch: arm64
      env: SCENARIO=lamp
    - arch: arm64
      env: SCENARIO=multiple
    # exclude jobs that should not be run on AMD64
    - arch: amd64
      env: SCENARIO=clients_arm

script:
  - molecule test --scenario-name $SCENARIO

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
