---

# Run borg package installation

- when: borgbackup_install_from_pkg|bool
  block:
    - name: install | set borg epel fact
      set_fact:
        borgbackup_install_epel: true
      when: >
        not borgbackup_install_epel
        and ansible_distribution != 'Fedora'

    - name: "Install EPEL repo"
      include_role:
        name: geerlingguy.repo-epel
      when: >
        borgbackup_install_epel
        and ansible_os_family == 'RedHat'

    - name: install | install borgbackup package
      package:
        name: "{{ borgbackup_package }}"
        state: present

# Run borg binary web installation related tasks

- when: not borgbackup_install_from_pkg|bool
  block:
    - name: install | set borg binary path
      set_fact:
        borgbackup_binary: "/usr/local/bin/borg"
        borgbackup_architecture: "{{ ansible_machine }}"

    - name: install | install borg binary from web
      get_url:
        dest: "{{ borgbackup_binary }}"
        checksum: "{{ borgbackup_release[borgbackup_architecture].checksum[borgbackup_version] }}"
        owner: "{{ borgbackup_owner }}"
        group: "{{ borgbackup_group }}"
        mode: "0755"
        url: "{{ borgbackup_release[borgbackup_architecture].url }}"
