---
- name: install borg backup
  get_url:
    dest: "/usr/local/bin/borg"
    checksum: "{{ borgbackup_checksum }}"
    owner: "root"
    group: "root"
    mode: "0755"
    url: "{{ borgbackup_download_url }}"
  tags: borginstall
