---
- include: install.yml
  when: >
    borgbackup_required == True or
    inventory_hostname in groups.borgbackup_servers

- include: borg-server.yml
  when: inventory_hostname in groups.borgbackup_servers

- include: borg-client.yml
  when: >
    borgbackup_required == True and
    inventory_hostname not in groups.borgbackup_servers

- include: management.yml
  when: >
    inventory_hostname in groups.borgbackup_management and
    inventory_hostname not in groups.borgbackup_servers
