---
driver:
  name: docker
lint:
  name: yamllint
scenario:
  name: centos
platforms:
  - name: centos-client-centos-8
    hostname: centos-client-centos-8
    image: centos:8
    networks:
      - name: centos-borg
    groups:
      - centos
      - clients
  - name: centos-server-centos-8
    hostname: centos-server-centos-8
    image: centos:8
    command: /lib/systemd/systemd
    privileged: true
    networks:
      - name: centos-borg
    groups:
      - centos
      - borgbackup_servers
  - name: centos-management-centos-8
    hostname: centos-management-centos-8
    command: /lib/systemd/systemd
    privileged: true
    image: centos:8
    networks:
      - name: centos-borg
    groups:
      - borgbackup_management
      - centos
      - clients
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      gather_timeout: 30
      interpreter_python: auto
      jinja2_extensions: jinja2.ext.do
      timeout: 30
    ssh_connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        borgbackup_appendonly: true
        borgbackup_servers:
          - fqdn: centos-server-centos-8
            user: borgds
            type: normal
            home: /var/backup/
            pool: repos
            options: ""
        borgbackup_retention:
          hourly: 12
          daily: 7
          weekly: 4
          monthly: 6
          yearly: 1
        borgbackup_management_station: centos-management-centos-8
        borgbackup_include:
          - "/etc"
          - "/root"
          - "/var/log"
          - "/home"
      borgbackup_servers:
        borgbackup_required: false
      borgbackup_management:
        borgbackup_management_user: root
        borgbackup_management_sshkey: |
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDXM5MuTbKbciopdHP314g0b72O5xaCf+4mt97bLPBwmW8UpOebWMkE+jYKET2B9fiOkyU9aWq+Tx7tfo31avN0nRf/VsxNupLcH605KdYOmw+EPjVDFLRXZb3j0AGDJM9YCd/KrwJlf8Tu4sXq0RhRNmqRBsBMjevpKCioQLzWJ1oCs1TLWxTS4nN7Jwy+Ou2gJEB7jKj907pFiCIPWRU4LLHlwE7DjunBr4THgE2Sj0tWkiYDKKoH++Rm62wVYL0oTLOJrQuqu52FEniPDgTnZwhy7b5MAHF5f2BscBorQxEkToWOVfX14Mzf+HC/arT2IPoE1Iv2XdWoiGiaWnyr
    host_vars:
      centos-client-centos-8:
        borgbackup_install_from_pkg: true
        borgbackup_passphrase: soo6Uabiex
      centos-management-centos-8:
        borgbackup_passphrase: 798uoknakjla
  lint:
    name: ansible-lint
    options:
      x: ["204"]
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
