---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint --exclude molecule
  flake8
platforms:
  - name: multiple-client-debian-10
    hostname: multiple-client-debian-10
    image: debian:10
    networks:
      - name: multiple-borg
    groups:
      - clients
  - name: multiple-client-ubuntu-bionic
    hostname: multiple-client-ubuntu-bionic
    image: ubuntu:bionic
    groups:
      - clients
    networks:
      - name: multiple-borg
  - name: multiple-server-debian-10
    hostname: multiple-server-debian-10
    image: debian:10
    networks:
      - name: multiple-borg
    groups:
      - borgbackup_servers
  - name: multiple-server-ubuntu-bionic
    hostname: multiple-server-ubuntu-bionic
    image: ubuntu:bionic
    networks:
      - name: multiple-borg
    groups:
      - borgbackup_servers
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      gather_timeout: 30
      interpreter_python: auto
      jinja2_extensions: jinja2.ext.do
      timeout: 30
    ssh_connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        borgbackup_appendonly: true
        borgbackup_servers:
          - fqdn: multiple-server-debian-10
            user: borgdj
            type: normal
            home: /var/backup/
            pool: repos
            options: ""
          - fqdn: multiple-server-ubuntu-bionic
            user: borgux
            type: normal
            home: /var/backup/
            pool: repos
            options: ""
        borgbackup_include:
          - "/etc"
          - "/root"
          - "/var/log"
          - "/home"
    host_vars:
      multiple-client-debian-10:
        borgbackup_install_from_pkg: true
        borgbackup_passphrase: soo6Uabiex
      multiple-client-ubuntu-bionic:
        borgbackup_passphrase: lidafruhkj
      multiple-server-ubuntu-bionic:
        borgbackup_install_from_pkg: true
        borgbackup_passphrase: oiasdfoain
scenario:
  name: multiple
verifier:
  name: testinfra
  options:
    verbose: true
