---
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: ${MOLECULE_PROJECT_DIRECTORY}/.yamllint
platforms:
  - name: ${MOLECULE_SCENARIO_NAME}-cds
    hostname: ${MOLECULE_SCENARIO_NAME}-cds
    image: debian:stretch
    networks:
      - name: ${MOLECULE_SCENARIO_NAME}-borg
  - name: ${MOLECULE_SCENARIO_NAME}-cub
    hostname: ${MOLECULE_SCENARIO_NAME}-cub
    image: ubuntu:bionic
    networks:
      - name: ${MOLECULE_SCENARIO_NAME}-borg
  - name: ${MOLECULE_SCENARIO_NAME}-sds
    hostname: ${MOLECULE_SCENARIO_NAME}-sds
    image: ubuntu:xenial
    networks:
      - name: ${MOLECULE_SCENARIO_NAME}-borg
    groups:
      - borgbackup_servers
  - name: ${MOLECULE_SCENARIO_NAME}-sub
    hostname: ${MOLECULE_SCENARIO_NAME}-sub
    image: ubuntu:bionic
    networks:
      - name: ${MOLECULE_SCENARIO_NAME}-borg
    groups:
      - borgbackup_servers
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        borgbackup_appendonly: true
        borgbackup_servers:
          - fqdn: ${MOLECULE_SCENARIO_NAME}-sds
            user: borgdj
            type: normal
            home: /var/backup/
            pool: repos
            options: ""
          - fqdn: ${MOLECULE_SCENARIO_NAME}-sub
            user: borgux
            type: normal
            home: /var/backup/
            pool: repos
            options: ""
        borgbackup_include:
          - "/etc"
          - "/root"
          - "/var/log"
          - "/home"
    host_vars:
      ${MOLECULE_SCENARIO_NAME}-cds:
        borgbackup_passphrase: soo6Uabiex
      ${MOLECULE_SCENARIO_NAME}-cub:
        borgbackup_passphrase: lidafruhkj
      ${MOLECULE_SCENARIO_NAME}-sub:
        borgbackup_passphrase: oiasdfoain
  lint:
    name: ansible-lint
scenario:
  name: multiple
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
