---
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ${MOLECULE_SCENARIO_NAME}-cds
    hostname: ${MOLECULE_SCENARIO_NAME}-cds
    image: debian:stretch
    networks:
      - name: ${MOLECULE_SCENARIO_NAME}-borg
    groups:
      - extra_opts
  - name: ${MOLECULE_SCENARIO_NAME}-sds
    hostname: ${MOLECULE_SCENARIO_NAME}-sds
    image: debian:stretch
    networks:
      - name: ${MOLECULE_SCENARIO_NAME}-borg
    groups:
      - borgbackup_servers
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        borgbackup_appendonly: true
        borgbackup_servers:
          - fqdn: ${MOLECULE_SCENARIO_NAME}-sds
            user: borgds
            type: normal
            home: /var/backup/
            pool: repos
            options: ""
    host_vars:
      ${MOLECULE_SCENARIO_NAME}-cds:
        borgbackup_passphrase: soo6Uabiex
        borgbackup_include:
          - "/etc"
          - "/root"
          - "/var/log"
          - "/home"
          - "/var/cache"
        borgbackup_exclude:
          - "/var/cache/apt"
        borgbackup_pre_commands:
          - "dpkg --get-selections"
        borgbackup_post_commands:
          - "apt list"
  lint:
    name: ansible-lint
scenario:
  name: extra_opts
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
