---
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ${MOLECULE_SCENARIO_NAME}-cds
    hostname: ${MOLECULE_SCENARIO_NAME}-cds
    image: debian:stretch
    networks:
      - name: ${MOLECULE_SCENARIO_NAME}-borg
    groups:
      - lamp
  - name: ${MOLECULE_SCENARIO_NAME}-sds
    hostname: ${MOLECULE_SCENARIO_NAME}-sds
    image: debian:stretch
    networks:
      - name: ${MOLECULE_SCENARIO_NAME}-borg
    groups:
      - borgbackup_servers
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      gather_timeout: 30
      interpreter_python: auto
      jinja2_extensions: jinja2.ext.do
      timeout: 30
    ssh_connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        borgbackup_appendonly: true
        borgbackup_servers:
          - fqdn: ${MOLECULE_SCENARIO_NAME}-sds
            user: borgds
            type: normal
            home: /var/backup/
            pool: repos
            options: ""
    host_vars:
      ${MOLECULE_SCENARIO_NAME}-cds:
        borgbackup_passphrase: soo6Uabiex
  lint:
    name: ansible-lint
    options:
      x: ["204"]
scenario:
  name: lamp
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
