---
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ${MOLECULE_SCENARIO_NAME}-cds
    hostname: ${MOLECULE_SCENARIO_NAME}-cds
    image: debian:stretch
    networks:
      - name: ${MOLECULE_SCENARIO_NAME}-borg
  - name: ${MOLECULE_SCENARIO_NAME}-sds
    hostname: ${MOLECULE_SCENARIO_NAME}-sds
    image: debian:stretch
    networks:
      - name: ${MOLECULE_SCENARIO_NAME}-borg
    groups:
      - borgbackup_servers
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        borgbackup_appendonly: true
        borgbackup_servers:
          - fqdn: ${MOLECULE_SCENARIO_NAME}-sds
            user: borgds
            type: normal
            home: /var/backup/
            pool: repos
            options: ""
        borgbackup_include:
          - "/etc"
          - "/root"
          - "/var/log"
          - "/home"
    host_vars:
      ${MOLECULE_SCENARIO_NAME}-cds:
        borgbackup_passphrase: soo6Uabiex
        borgbackup_pre_commands:
          - "touch /var/log/pre_command"
        borgbackup_post_commands:
          - "touch /var/log/post_command"
  lint:
    name: ansible-lint
scenario:
  name: commands
verifier:
  name: goss
  lint:
    name: yamllint
