---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint --exclude molecule
  flake8
platforms:
  - name: clients-ubuntu-bionic
    hostname: clients-ubuntu-bionic
    image: ubuntu:bionic
    networks:
      - name: clients-borg
    groups:
      - clients
  - name: clients-ubuntu-bionic-pkg
    hostname: clients-ubuntu-bionic
    image: ubuntu:bionic
    networks:
      - name: clients-borg
    groups:
      - clients
  - name: clients-ubuntu-focal
    hostname: clients-ubuntu-focal
    image: ubuntu:focal
    networks:
      - name: clients-borg
    groups:
      - clients
  - name: clients-ubuntu-focal-pkg
    hostname: clients-ubuntu-focal
    image: ubuntu:focal
    networks:
      - name: clients-borg
    groups:
      - clients
  - name: clients-debian-10
    hostname: clients-debian-10
    image: debian:10
    networks:
      - name: clients-borg
    groups:
      - clients
  - name: clients-debian-10-pkg
    hostname: clients-debian-10
    image: debian:10
    networks:
      - name: clients-borg
    groups:
      - clients
  - name: clients-debian-11
    hostname: clients-debian-11
    image: debian:11
    networks:
      - name: clients-borg
    groups:
      - clients
  - name: clients-debian-11-pkg
    hostname: clients-debian-11
    image: debian:11
    networks:
      - name: clients-borg
    groups:
      - clients
  - name: clients-debian-8
    hostname: clients-debian-8
    image: debian:8
    networks:
      - name: clients-borg
    groups:
      - clients
  - name: clients-rocky-8
    hostname: clients-rocky-8
    image: rockylinux/rockylinux:8
    networks:
      - name: clients-borg
    groups:
      - centos
      - clients
  - name: clients-rocky-8-pkg
    hostname: clients-rocky-8
    image: rockylinux/rockylinux:8
    networks:
      - name: clients-borg
    groups:
      - centos
      - clients
  - name: clients-centos-7
    hostname: clients-centos-7
    image: centos:7
    networks:
      - name: clients-borg
    groups:
      - centos
      - clients
  - name: clients-centos-7-pkg
    hostname: clients-centos-7
    image: centos:7
    networks:
      - name: clients-borg
    groups:
      - centos
      - clients
  - name: clients-fedora-35
    hostname: clients-fedora-35
    image: fedora:35
    networks:
      - name: clients-borg
    groups:
      - centos
      - clients
  - name: clients-fedora-35-pkg
    hostname: clients-fedora-35-pkg
    image: fedora:35
    networks:
      - name: clients-borg
    groups:
      - centos
      - clients
  - name: clients-server-debian-10
    hostname: clients-server-debian-10
    image: debian:10
    networks:
      - name: clients-borg
    groups:
      - borgbackup_servers
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      gather_timeout: 30
      interpreter_python: auto
      jinja2_extensions: jinja2.ext.do
      timeout: 30
    ssh_connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        borgbackup_appendonly: true
        borgbackup_servers:
          - fqdn: clients-server-debian-10
            user: borgds
            type: normal
            home: /var/backup/
            pool: repos
            options: ""
        borgbackup_include:
          - "/etc"
          - "/root"
          - "/var/log"
          - "/home"
    host_vars:
      clients-ubuntu-bionic:
        borgbackup_passphrase: soo6Uabiex
      clients-ubuntu-bionic-pkg:
        borgbackup_install_from_pkg: true
        borgbackup_passphrase: soo6Uabiexpkg
      clients-ubuntu-focal:
        borgbackup_passphrase: ooFeila1ie
      clients-ubuntu-focal-pkg:
        borgbackup_install_from_pkg: true
        borgbackup_passphrase: ooFeila1iepkg
      clients-debian-10:
        borgbackup_passphrase: eewoo7paf6J
      clients-debian-10-pkg:
        borgbackup_install_from_pkg: true
        borgbackup_passphrase: eewoo7paf6Jpkg
      clients-debian-11:
        borgbackup_passphrase: aef1Iekahpi
      clients-debian-11-pkg:
        borgbackup_install_from_pkg: true
        borgbackup_passphrase: aef1Iekahpipkg
      clients-debian-8:
        borgbackup_passphrase: aef1Iekasfs
      clients-rocky-8:
        ansible_python_interpreter: /usr/bin/python3
        borgbackup_passphrase: ASFQiejasdf
      clients-rocky-8-pkg:
        ansible_python_interpreter: /usr/bin/python3
        borgbackup_install_from_pkg: true
        borgbackup_passphrase: ASFQiejasdfpkg
      clients-centos-7:
        borgbackup_passphrase: ASFQiejwasd
      clients-centos-7-pkg:
        borgbackup_install_from_pkg: true
        borgbackup_passphrase: ASFQiejwasdpkg
      clients-fedora-35:
        borgbackup_passphrase: sdfqjqoais
      clients-fedora-35-pkg:
        borgbackup_install_from_pkg: true
        borgbackup_passphrase: sdfqjqoaispkg
scenario:
  name: clients
verifier:
  name: testinfra
  options:
    verbose: true
